# Generated by Django 3.2.9 on 2021-11-10 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTask', '0003_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 12, 50, 38, 803836)),
        ),
    ]
